---
header: |
  #!/usr/bin/env ruby
  # frozen_string_literal: false

  require "simplecov"

  ::SimpleCov.command_name "Brutal test suite"
  ::SimpleCov.start

  require "./lib/spectus"
  require "matchi/helper"

  self.class.include Matchi::Helper

subject: |
  begin
    Spectus.%{level}(%{matcher}).call { "foo".%{challenge} }
  rescue Expresenter::Fail => e
    e
  end

contexts:
  challenge:
    - "upcase"
    - "itself"
    - 'gsub!("f", "b")'
    - "boom"
    - "empty?(4)"
  level:
    - must
    - should
    - may
    - must_not
    - should_not
    - "must!"
    - "should!"
    - "may!"
    - "must_not!"
    - "should_not!"
  matcher:
    - "raise_exception(NoMethodError)"
    - "raise_exception(ArgumentError)"
    - 'eql("foo")'
    - "equal(42)"

actuals:
  - "%{subject}.level"
  - "%{subject}.to_sym"
  - "%{subject}.error?"
  - "%{subject}.failure?"
  - "%{subject}.info?"
  - "%{subject}.negate?"
  - "%{subject}.failed?"
  - "%{subject}.passed?"
  - "%{subject}.success?"
  - "%{subject}.warning?"
  - "%{subject}.emoji"
  - "%{subject}.char"
  - "%{subject}.colored_char"
  - "%{subject}.message"
  - "%{subject}.to_s"
  - "%{subject}.colored_string"
  - "%{subject}.inspect"
  - "%{subject}.actual.inspect"
  - "%{subject}.expected"
  - "%{subject}.error.class"
  - "%{subject}.got.class"
