inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

  Exclude:
    - test.rb

require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/MixinUsage:
  Exclude:
    - README.md
