require:
  - rubocop-performance
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

  Exclude:
    - test.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes
